# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

matrix:
  include:
    - env: TOXENV=django11
    - env: TOXENV=quality
    - env: TOXENV=docs

cache:
  - pip
  
before_install:
  - pip install --upgrade pip==20.0.1

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov
